### ISSUE TITLE
Merge __init__ into class definition

### ISSUE THREAD

**Issue by agjohnson** [rtfd/sphinx-autoapi#107]
Currently, these are listed separately, so there is a class definition and then an `__init__` object under that listing. The two should be merged under the class definition.

**Comment by AWhetter** [comment]
I have a working solution for this based on the [autoclass_content](http://www.sphinx-doc.org/en/master/ext/autodoc.html#confval-autoclass_content) configuration option in autodoc. I'll open a PR in the next couple of weeks.
