### ISSUE TITLE
Remove reference to epydoc and supporting Python 2 only

### ISSUE THREAD

**Issue by peterjc** [rtfd/sphinx-autoapi#120]
The README.rst file currently says:

> Currently Implemented
> ---------------------
>  
> * Python (2 only -- Epydoc doesn't support Python 3)
> * .NET
> * Go
> * Javascript

Note ``epydoc`` is a no longer maintained Python module which has not been updated for nearly 10 years:

https://pypi.python.org/pypi/epydoc
http://epydoc.sourceforge.net/

Searching the code this is the only mention of epydoc - so I believe the README entry is out of date.

Reading the code, I think you use the Python standard library modules ``ast`` and ``tokenize`` instead, so this ought to work on Python 3 too. Indeed the ``.travis.yml`` file explicitly tests under Python 3.

**Comment by agjohnson** [comment]
We've had a number of discussions around this, we want to avoid maintaining another AST traversal mechanism. Supporting python 2 and python 3 would require maintaining two separate ast traversal patterns, and quite frankly, even one is plenty of work -- hence epydoc.

Currently, we are using `pydocstyle` to parse the python code, so the documentation is out of date.

**Comment by humitos** [comment]
pdoc (http://pdoc.burntsushi.net/pdoc) is something that could be useful to include in this discussion.

**Comment by ericholscher** [comment]
https://github.com/BurntSushi/pdoc/issues/82

**Comment by peterjc** [comment]
Thanks - the README file is much clearer now :)
