### ISSUE TITLE
javascript domain: bug on windows build

### ISSUE THREAD

**Issue by fredbi** [rtfd/sphinx-autoapi#125]
In mappers/javascript.py

On windows, the jsdoc command is actually named jsdoc.cmd and is not recognized by subprocess().

Proposed: 

```
subcmd = 'jsdoc'
if os.name == 'nt':
    subcmd='.'.join([subcmd,'cmd'])
parsed_data = json.loads(subprocess.check_output([subcmd, '-X', path])) 
````

Could be nice to support an optional path for these commands in conf.py

**Comment by agjohnson** [comment]
Yeah, perhaps a config option is the most correct fix here? I'm not familiar with windows development with node, but it seems like this shouldn't be magic that we need to use. Rather, is there something we're not doing with the subprocess call that would imply a `.exe/.cmd` prefix?

**Comment by fredbi** [comment]
I have been checking the subprocess doc and nothing looks like that. Safest to check the os in our code I guess.

Optionnally configuring paths for required tools would be a nice bonus.
