### ISSUE TITLE
GoLang sphinxcontrib.golangdomain extension not being imported

### ISSUE THREAD

**Issue by v-sinitsa** [rtfd/sphinx-autoapi#133]
Im trying to get autoapi setup to work with go lang but I keep getting this error message:

`Running Sphinx v1.7.0

Extension error:
Could not import extension sphinxcontrib.golangdomain (exception: No module named compat)
make: *** [html] Error 2`

Has anyone encountered this issue before?

**Comment by AWhetter** [comment]
There's an issue open with sphinxcontrib-golangdomain (https://bitbucket.org/ymotongpoo/sphinxcontrib-golangdomain/issues/5/incompatible-with-sphinx-17). A fix has already been merged, we're just waiting for it to be released. I would be great if you could make a comment on that issue to encourage the maintainer to make a release.
