### ISSUE TITLE
Support for Python type annotations

### ISSUE THREAD

**Issue by AWhetter** [rtfd/sphinx-autoapi#139]
The astroid integration hasn't been tested with type annotations at all. We should check if they're being output at the moment, and if not then output type annotations with how Sphinx normally would.

**Comment by deeplook** [comment]
In what state is this issue right now? I'm trying to get https://github.com/agronholm/sphinx-autodoc-typehints working with this package (https://github.com/rtfd/sphinx-autoapi), but I'm not seeing any expected outcome.

**Comment by AWhetter** [comment]
Are you using the autodoc directives or the jinja templates?

**Comment by AWhetter** [comment]
I've added support for type annotations in the documentation generation and the autodoc directives. Complete support for type comments (#162) is blocked by an issue in astroid.

autoapi won't work with sphinx-autodoc-typehints because it expects to be passed live Python objects by autodoc, but our autodoc directives can only supply autoapi objects. To support the features of sphinx-autodoc-typehints we would have to make our own autoapi equivalent.
