### ISSUE TITLE
Attributes duplicated when documented in Python class docstring

### ISSUE THREAD

**Issue by AWhetter** [rtfd/sphinx-autoapi#146]
If an attribute is documented in the class docstring and also assigned to in `__init__`, the attribute is documented twice. It should get documented only once. If it is documented in both places, I think it is fine for the choice of which docstring to use to be arbitrary.

```
class MyClass:
    """My class does stuff.

    Attributes:
        thing (object): A thing.
    """
    def __init__(self):
        self.thing = 5
```

**Comment by AWhetter** [comment]
I'm closing this because we can't get around it without parsing the docstring, which isn't something that we want to get into.

**Comment by carlosgmartin** [comment]
@AWhetter Is there any way around this duplication?

**Comment by AWhetter** [comment]
This is explained here: https://github.com/readthedocs/sphinx-autoapi/issues/476#issuecomment-2316718949
