### ISSUE TITLE
Error when resolving wilcard imports

### ISSUE THREAD

**Issue by AWhetter** [rtfd/sphinx-autoapi#156]
When a package imports from itself using a wildcard import, the extension tries to find an object with a '*' in its name. It can't so it fails with a KeyError.
Instead, we'll have to add a special case where wildcard imports instead create new placeholders under that module for everything that gets imported.

**Comment by mangopipeline** [comment]
Damn...
Well I just spent the last few hours refactoring a large code base.

I have no wild card import anywhere...

And the issue did not go away :(

**Comment by mangopipeline** [comment]
Could it be that relative imports are breaking it?
