### ISSUE TITLE
Encoding error: 'ascii' codec can't decode byte 0xf0 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by mangopipeline** [rtfd/sphinx-autoapi#159]
Happens during he "Rendering Data" step.
Any ideas?

auto api is also logging sevral "cannot resolve import" messages like the one below...

WARNING: Cannot resolve import of mango.mapis.icon_lib in mango.mutils.qccs

[sphinx-err-sced7_.log](https://github.com/rtfd/sphinx-autoapi/files/2799838/sphinx-err-sced7_.log)

**Comment by AWhetter** [comment]
Do you have a data object (module level assignment) with a unicode value somewhere? It might be that we need to call `self._encode()` on data values as well as the docstring (https://github.com/rtfd/sphinx-autoapi/blob/63bbe719c667544a6780ee7f8e2fce1a0ffb6da7/autoapi/mappers/python.py#L578).

The import resolution errors are telling you that autoapi could not find `icon_lib` in `mango.mapis` from an import in `mango.mutil.qccs`. There's not much that I can do to debug it without access to the source code that its parsing. Is the import correct?

**Comment by AWhetter** [comment]
If you put a breakpoint in `PythonMapperBase.rendered` you can use `self` to figure out what object is being rendered by looking at `self.obj["full_name"]`.
```python
@property
def rendered(self):
    "Shortcut to render an object in templates."
    try:
        return self.render()
    except Exception:
        import pdb; pdb.set_trace()
        raise
```

Although the fact that you need to use pdb is maybe an indication that we need to improve the debug logging.

**Comment by AWhetter** [comment]
I've added debug logging, so you shouldn't need to use pdb anymore. If you give `sphinx-build` the `-v` flag it will print out which module or package is being rendered. If you give it `-vv`, it will also print which object is being rendered.

**Comment by mangopipeline** [comment]
That’s awesome I’ll give it a go this weekend :)
