### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by ericholscher** [rtfd/sphinx-autoapi#160]
Hey @AWhetter -- great job over the last little while on this! I'm wondering if we should look at releasing a 1.0 and removing the warnings in the docs/README about it being pre-release. 

I'd also like to start promoting this as an alternative to `autodoc` heavily, since I think it would make life a lot easier for a lot of Sphinx & particularly Read the Docs users.

What do you think?

**Comment by ericholscher** [comment]
+1 on finishing up the items listed.

> I've focused almost solely on the Python side of things. I know that the .NET stuff doesn't work because I've been able to reproduce #79. I think we can go ahead and remove the pre-release warning but we could keep a status table to indicate how complete the implementation is for each language?

Yea, I think that's a good idea. The .Net stuff is definitely old, and I like the idea of having some kind of `:status:` badge on each language. 

> I also have a personal goal to present this to a local Python user group to get feedback, and maybe even do a lightning talk on it at PyCon.

This is a great idea! We'll also try and get a blog post put together on the RTD blog, and also highlight it in our docs in a similar timeframe 👍

**Comment by deeplook** [comment]
I would also like to see some description about rendering type information as I've commented in https://github.com/rtfd/sphinx-autoapi/issues/139#issuecomment-483186559. It now almost looks to me like https://github.com/agronholm/sphinx-autodoc-typehints cannot be used by `sphinx-autoapi`, but then how can I get typing info included?

**Comment by AWhetter** [comment]
@ericholscher Everything should be good to go. I'm going to do some final tests next week and then release version 1.0!
Unfortunately I won't make it to PyCon this year but I wish you all the best with the sprints!

**Comment by ericholscher** [comment]
Sounds great. Sad we won't be able to catch up at Pycon, but I will be there doing some promotion :) Let me know if I can help.

**Comment by AWhetter** [comment]
Version 1.0.0 is out!

**Comment by ericholscher** [comment]
Awesome -- let me know if you want to write up a blog post, or I will add it to my queue of posts to write :)
