### ISSUE TITLE
The dotnet mapper should restore packages using `dnu restore` before running docfx

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#36]
Docfx needs the packages to be restored in order to generate complete metadata. For example, if you look at the inheritance hierarchy for [IdentityDbContext](http://aspnet-docs-example.readthedocs.org/en/latest/autoapi/Microsoft/AspNet/Identity/EntityFramework/IdentityDbContext/index.html#Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext) you will see that the base `DbContext` type doesn’t have a namespace. That’s because this type is defined in a separate package and docfx didn’t have access to its metadata.

**Comment by agjohnson** [comment]
Thoughts on if this would always be required for other projects? It would definitely make sense as a configurable option, defaulted to `False` maybe to save on computing resources?

**Comment by danroth27** [comment]
I'm having second thoughts about this request. In addition to handling restoring packages for DNX based projects (project.json) you probably also need to restore packages for csproj/vsproj based projects that are using a packages.config file. I'm not sure the .NET mapper should have to do all that. Maybe it's best to keep this an external concern to autoapi.

**Comment by agjohnson** [comment]
On second thought, this might make more sense outside of the autoapi. This would probably be more useful as a feature of RTD, as additional configuration inside https://github.com/rtfd/readthedocs-build.

**Comment by danroth27** [comment]
Closing since I don't think this is a concern of the autoapi.
