### ISSUE TITLE
Default output folder for docfx changed to _site

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#45]
Looks like the .NET mapper assumes that the default output folder will be `_api_`, but it recently go changed to `_site`. The .NET mapper should probably explicitly specify the output folder when running docfx to make sure it can find the output metadata.

**Comment by agjohnson** [comment]
This can be moved to a mapper-specific configuration option, though we should also specify the path with the `docfx` option `-o or --output`.

**Comment by agjohnson** [comment]
It appears the `-o` option only prepends to the output path, it never overrides. Forcing `-o _api` creates an output path `-o _api/_api`. If there is a dest setting of 'docs/_api_` in the `docfx.json` file, forcing `-o _api` creates an output path of `_api/docs/_api_`. So, seems we can't use this to set a path quite yet. 

Not sure if this is a docfx-dev vs docfx mainline issue, but I get the output path of `_api`. Addressing this in a PR, if the path does change to `_site` we can update again.
