### ISSUE TITLE
Move build outputs under _build

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#47]
It would be nice if the intermediate build outputs from autoapi were put under the _build folder. That way `make clean` would clean them out without having to modify anything.

**Comment by agjohnson** [comment]
Another option here is ensuring the paths for output are clean before the build as well as after the build. These files should normally be removed after each run, but there are some edge cases where these files can persist.

**Comment by danroth27** [comment]
Yeah, I realized that some of the folders I was seeing sticking around after doing a clean were actually due to some buggy changes I had made to the .NET mapper.

The autoapi folder will get created and stick around if you set the `autoapi_keep_files` option, but I think that's ok as this folder contains the generated rst files.
