### ISSUE TITLE
No link generated for return types

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#50]
When I run autoapi on the master branch of the ASP.NET [JsonPatch](https://github.com/aspnet/jsonpatch) repo, I don't get links generated for return types.

For example, the [OperationType](https://github.com/aspnet/JsonPatch/blob/master/src/Microsoft.AspNet.JsonPatch/Operations/OperationBase.cs#L12) property on the OperationBase type returns an [OperationType](https://github.com/aspnet/JsonPatch/blob/master/src/Microsoft.AspNet.JsonPatch/Operations/OperationType.cs) enum. The generated RST looks like this:

```
    .. dn:property:: Microsoft.AspNet.JsonPatch.Operations.OperationBase.OperationType
    
        
        :rtype: Microsoft.AspNet.JsonPatch.Operations.OperationType
```

The generated docs contain the OperationType enum, but the generated return type doesn't link to it.

**Comment by agjohnson** [comment]
Moved this to rtfd/sphinxcontrib-dotnetdomain#52
