### ISSUE TITLE
Generated .NET API docs for a type should include the namespace and assembly name

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#60]
Existing MSDN docs for .NET types include the namespace and assembly name near the top of the page. For example https://msdn.microsoft.com/en-us/library/system.console(v=vs.110).aspx:

![image](https://cloud.githubusercontent.com/assets/1874516/12797743/54fc6d92-ca7a-11e5-8644-298c4b4bb34e.png)

It would be great if autoapi did this as well. I believe the metadata is already provided by docfx.

**Comment by agjohnson** [comment]
Looking at the generated data, the assembly names for `Identity` are `Microsoft.AspNet.Identity`. It seems we can't assume this will be an object with an id to be referenced?

**Comment by danroth27** [comment]
@vacancy @chenkennt Can you guys point @agjohnson at the right metadata to use?

**Comment by chenkennt** [comment]
Namespace is a reference to another object, assembly is just a plain text.

**Comment by agjohnson** [comment]
Great, I'm treating it as such currently, assuming there will be a string that can't be referenced eventually. Sounds like this is the way to go.

**Comment by agjohnson** [comment]
Closing this for now, it might make sense to dedupe this display eventually, in the case that the assembly and namespace are matching/etc.
