### ISSUE TITLE
Allow which toctree node the entries are placed under to be configurable

### ISSUE THREAD

**Issue by AWhetter** [rtfd/sphinx-autoapi#97]
It would be nice to be able to configure which toctree node autoapi adds itself to. Currently this is hardcoded to `"index"` (https://github.com/rtfd/sphinx-autoapi/blob/5529237fb5012039d248abccdf61865aace5fb32/autoapi/extension.py#L117).
For example I have the case where my documentation is split into a user and technical section. I want the API docs to reside under the technical section rather than at the top level.

The README says

> AutoAPI will automatically add itself to the last TOCTree in your top-level index.rst.
> ...
> We hope to be able to dynamically add items into the TOCTree, and remove this step. However, it is currently required.

I don't really know what this means but it sounds like it would mean implementing a similar thing?

**Comment by AWhetter** [comment]
Closing because I think it makes more sense for a user to set `autoapi_add_toctree_entry` to False and then add a toctree entry for `/autoapi/index.rst` wherever they want autoapi included.

We ever go as far as to put `/autoapi/<my_package>/index.rst` in our toctree so that we don't get the top level autoapi index file.

**Comment by sammorley-short** [comment]
@AWhetter I tried your suggested solution and it didn't work (`autoapi_add_toctree_entry = False` and then adding `/autoapi/index.rst` to the specific toctree directive where I wanted to add it.

Did something change or is this still supported?
